### PR TITLE
add PanCamLabel

### PR DESCRIPTION
**Pull request by aspiringLich**
Allow users to order PanCamPlugin's systems by referencing it via PanCamLabel

### CODE REVIEW

**Comment by johanhelsing** [comment]
Thanks! Having such a label public makes sense. Only comment is perhaps the name, it was not immediately clear to me that this is a *system* label.

Do you know if there is a naming convention in other plugins?

**Comment by aspiringLich** [comment]
Hm, not that I'm aware of, skimming through some other plugins this doesn't seem to be a commonly implemented practice.

I guess that's fair, this probably usually isn't a big issue as plugins are somewhat self-contained (isn't even that big of an issue in my case lol). Maybe `PanCamSystemLabel` would be a better name with it, however.

**Comment by johanhelsing** [comment]
I found 3-4 plugins that expose system labels and they all use an enum called `CrateNameSystem`. And then list various systems. Sometimes more general labels that cover more than one system.

In this case we probably don't want to leak implementation details into the public api. So probably best to go with just one label for both systems.

I'm leaning towards either a `struct PanCamSystem` or an enum with one value `PanCamSystem::Update` or something for both systems.

**Comment by aspiringLich** [comment]
hm, yeah either of those sound like decent conventions, i guess the struct would be more fitting since i cant imagine the pancam getting anything else significant that would need specific ordering, and if that happens well someone could always open another pr

**Comment by johanhelsing** [comment]
Sounds good 👍 

I just found out this will all change (for the better) when the bevy stageless rfc is implemented anyway.

**Review by johanhelsing — APPROVED** [review]

**Comment by johanhelsing** [comment]
Thanks!

**Comment by aspiringLich** [comment]
👍

**Pull request merged**
